In [2]:
#单样本t检验
"""确定样本均值是否与已知或假设的总体均值具有统计学差异"""
from scipy.stats import ttest_1samp
import numpy as np
#ages = np.genfromtxt('ages.csv')
#print (ages)
ages_mean = np.mean(ages)
print ages_mean

tset, pval = ttest_1samp(ages, 30)
print ('p-value', pval)
if pval < 0.05:
    print ('we are rejecting null hypothesis')
else:
    print ('we are accepting null hypothesis')

In [4]:
#双样本t检验
"""用于比较两个独立组的平均值，以确定是否有统计证据表明相关的人口均值存在显著差异"""
from scipy.stats import ttest_ind
import numpy as np
week1 = np.genfromtxt('week1.csv', delimiter=',')
week2 = np.genfromtxt('week2.csv', delimiter=',')
print (week1)
print ('week2 data:-\n')
print (week2)
week1_mean = np.mean(week1)
week2_mean = np.mean(week2)
print ('week1 mean value:', week1_mean)
print ('week2 mean value:', week2_mean)
week1_std = np.std(week1)
week2_std = np.std(week2)
print ('week1 std value:', week1_std)
print ('week2 std value:', week2_std)
ttest, pval = ttest_ind(week1, week2)
print ('p-value', pval)
if pval < 0.05:
    print ('we are rejecting null hypothesis')
else:
    print ('we are accepting null hypothesis')

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2006-01-03,127.000000,124.389999,125.190002,126.699997,73256700.0,96.358261
2006-01-04,127.489998,126.699997,126.860001,127.300003,51899600.0,96.814583
2006-01-05,127.589996,126.879997,127.150002,127.379997,47307500.0,96.875389
2006-01-06,128.580002,127.360001,128.020004,128.440002,62885900.0,97.681541
2006-01-09,129.059998,128.380005,128.419998,128.770004,43527400.0,97.932510

In [5]:
#配对样本t检验
"""单变量测试，测试2个相关变量之间的显著差异"""
import pandas as pd
from scipy import stats
df = pd.read_csv('blood_pressure.csv')
df[['bp_before', 'bp_after']].describe()
ttest, pval = ttest_rel(df['bp_before'], df['bp_after'])
print (pval)
if pval < 0.05:
    print ('we are rejecting null hypothesis')
else:
    print ('we are accepting null hypothesis')

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2009-12-24,112.599998,112.000000,112.190002,112.480003,39677500.0,92.972710
2009-12-28,112.989998,112.320000,112.900002,112.720001,87508500.0,93.171059
2009-12-29,113.029999,112.550003,113.010002,112.559998,80572500.0,93.038811
2009-12-30,112.650002,112.169998,112.230003,112.519997,73138400.0,93.005737
2009-12-31,112.800003,111.389999,112.769997,111.440002,90637900.0,92.113052

In [6]:
#z检验，样本量超过30个，如156个单样本z检验
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests
ztest, pval = stests.ztest(df['bp_before'], x2=None, value=156)
print (float(pval))
if pval < 0.05:
    print ('we are rejecting null hypothesis')
else:
    print ('we are accepting null hypothesis')
#双样本z检验——检查两个独立的数据组并确定两个组的样本均值是否相等
ztest, pval1 = stests.ztest(df['bp_before'], x2=df['bp_after'], value=0, alternative='two-sided')
print (float(pval1))
if pval1 < 0.05:
    print ('we are rejecting null hypothesis')
else:
    print ('we are accepting null hypothesis')

Date
2006-01-03         NaN
2006-01-04    0.004736
2006-01-05    0.000628
2006-01-06    0.008322
2006-01-09    0.002569
Name: Adj Close, dtype: float64